Version 0
SymbolType BLOCK
RECTANGLE Normal 0 -128 112 0
PIN 0 -112 LEFT 8
PINATTR PinName Tx
PINATTR SpiceOrder 1
PIN 0 -80 LEFT 8
PINATTR PinName Rx
PINATTR SpiceOrder 2
PIN 0 -16 LEFT 8
PINATTR PinName GND
PINATTR SpiceOrder 3
PIN 0 -48 LEFT 8
PINATTR PinName VCC
PINATTR SpiceOrder 4
